name: Deploy Minecraft Server Functions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: linear-skill-471411-n9
  REGION: europe-west1
  MINECRAFT_ZONE: us-central1-f
  MINECRAFT_INSTANCE: instance-20250920-120747
  MINECRAFT_FIREWALL_RULE: minecraft-server-ingress

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Only run on main/master branch pushes
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy Start Server Function
      run: |
        gcloud run deploy minecraft-start-server \
          --source . \
          --function startServer \
          --base-image nodejs20 \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_PROJECT=$PROJECT_ID,MINECRAFT_ZONE=$MINECRAFT_ZONE,MINECRAFT_INSTANCE=$MINECRAFT_INSTANCE" \
          --max-instances=1 \
          --timeout=300 \
          --memory=512Mi

    - name: Deploy Stop Server Function
      run: |
        gcloud run deploy minecraft-stop-server \
          --source . \
          --function stopServer \
          --base-image nodejs20 \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_PROJECT=$PROJECT_ID,MINECRAFT_ZONE=$MINECRAFT_ZONE,MINECRAFT_INSTANCE=$MINECRAFT_INSTANCE" \
          --max-instances=1 \
          --timeout=300 \
          --memory=512Mi

    - name: Deploy Add Friend Function
      run: |
        gcloud run deploy minecraft-add-friend \
          --source . \
          --function addFriend \
          --base-image nodejs20 \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_PROJECT=$PROJECT_ID,MINECRAFT_ZONE=$MINECRAFT_ZONE,MINECRAFT_INSTANCE=$MINECRAFT_INSTANCE,MINECRAFT_FIREWALL_RULE=$MINECRAFT_FIREWALL_RULE" \
          --max-instances=5 \
          --timeout=180 \
          --memory=512Mi

    - name: Get Function URLs
      run: |
        echo "### Deployment Complete! 🚀" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Function URLs:**" >> $GITHUB_STEP_SUMMARY
        echo "- Start Server: $(gcloud run services describe minecraft-start-server --region=$REGION --format='value(status.url)')" >> $GITHUB_STEP_SUMMARY
        echo "- Stop Server: $(gcloud run services describe minecraft-stop-server --region=$REGION --format='value(status.url)')" >> $GITHUB_STEP_SUMMARY  
        echo "- Add Friend: $(gcloud run services describe minecraft-add-friend --region=$REGION --format='value(status.url)')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:**" >> $GITHUB_STEP_SUMMARY
        echo "- Project: $PROJECT_ID" >> $GITHUB_STEP_SUMMARY
        echo "- Region: $REGION" >> $GITHUB_STEP_SUMMARY
        echo "- Minecraft Zone: $MINECRAFT_ZONE" >> $GITHUB_STEP_SUMMARY
        echo "- Minecraft Instance: $MINECRAFT_INSTANCE" >> $GITHUB_STEP_SUMMARY
        echo "- Firewall Rule: $MINECRAFT_FIREWALL_RULE" >> $GITHUB_STEP_SUMMARY